language: ruby
cache: bundler
sudo: false
dist: trusty
matrix:
  fast_finish: true
  include:
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4.0
    - rvm: 2.4.1
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.4.1
notifications:
  email: false
